server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev
  
  application:
    name: student-assessment-system
    # Default base URL can be overridden per profile
    base-url: ${APP_BASE_URL:http://localhost:5173}

  # 数据源配置
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:student_assessment_system}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  # Redis配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      location: ${java.io.tmpdir}
  
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:3000ms}
      password: ${REDIS_PASSWORD:}

# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.noncore.assessment.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
    default-executor-type: reuse
    default-statement-timeout: 30
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# JWT配置
jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:86400000}  # 24小时 (毫秒)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7天 (毫秒)

# 文件上传配置
file:
  upload-dir: ./uploads
  max-size: 50MB
  allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar,mp4,mov,avi,mkv,webm
  purpose-max-sizes: course_material=1GB,course_video=1GB

# 日志配置
logging:
  level:
    com.noncore.assessment: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/application.log

# SpringDoc配置 (Swagger)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  packages-to-scan: com.noncore.assessment.controller
  show-actuator: false 

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

# AI 集成配置（DeepSeek/OpenAI 兼容）
ai:
  default-provider: ${AI_DEFAULT_PROVIDER:openrouter}
  system-prompt-path: ${AI_SYSTEM_PROMPT_PATH:classpath:/prompts/essay_evaluation_system_prompt.txt}
  proxy:
    enabled: ${AI_PROXY_ENABLED:true}
    always-use-proxy: ${AI_ALWAYS_USE_PROXY:false}
    auto-retry-with-proxy: ${AI_AUTO_RETRY_WITH_PROXY:true}
    host: ${AI_PROXY_HOST:127.0.0.1}
    port: ${AI_PROXY_PORT:7897}
    type: ${AI_PROXY_TYPE:HTTP}
    connect-timeout-ms: ${AI_PROXY_CONNECT_TIMEOUT_MS:10000}
    read-timeout-ms: ${AI_PROXY_READ_TIMEOUT_MS:120000}
  retry:
    max-attempts: ${AI_RETRY_MAX_ATTEMPTS:3}
    backoff-ms: ${AI_RETRY_BACKOFF_MS:800}
    jitter-ms: ${AI_RETRY_JITTER_MS:200}
  providers:
    openrouter:
      base-url: ${OPENROUTER_BASE_URL:https://openrouter.ai/api}
      api-key: ${OPENROUTER_API_KEY:${DEEPSEEK_API_KEY:}}
    google:
      base-url: ${GOOGLE_API_BASE_URL:https://generativelanguage.googleapis.com}
      api-key: ${GOOGLE_API_KEY:}
  deepseek:
    model: ${DEEPSEEK_MODEL:deepseek/deepseek-chat-v3.1}

# 安全配置
security:
  cors:
    allowed-origins: http://localhost:5173,http://127.0.0.1:5173
  jwt:
    public-urls:
      - /auth/login
      - /auth/register
      - /auth/verify-email
      - /auth/check-username
      - /auth/check-email
      - /users/forgot-password
      - /users/reset-password
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /swagger-resources/**
      - /webjars/**
      - /actuator/health
      - /actuator/info
      - /static/**
      - /public/**
      - /favicon.ico
      - /files/download/public/**